### PR TITLE
Add make/nix-based linux build

### PR DESCRIPTION
**Pull request by moben**
If all dependencies are available on the host system, then the Makefile
can just be used as is and will set up a wineprefix and the UDK and then build lwce.

Needs:
  * gnumake
  * bash
  * wine
  * winetricks
  * dos2unix

Also added a nix-based wrapper around this that should be usable on any
Linux system if `nix` can be installed and will fetch all dependencies
from nixpkgs in versions that have been tested. One upside is that newer wine
versions occasionally break and here everything is pinned in the repo and
distribution independent. Another advantage is that it's pretty good at caching
the UDK setup.

Just run `nix build` or `nix-build`, all outputs will be in `result/`
Should also work with docker via https://hub.docker.com/r/nixos/nix

More magic:

        % nix build github:chrishayesmu/XCOM-LW-CommunityEdition
        % tree result/
        result
        ├── Config
        │   ├── DefaultLWCEBaseStrategyGame.ini
        │   ├── DefaultLWCEBaseTacticalGame.ini
        │   ├── DefaultLWCEClasses.ini
        │   ├── DefaultLWCEMods.ini
        │   └── DefaultLWCEQualityOfLife.ini
        ├── CookedPCConsole
        │   └── XComLongWarCommunityEdition.u
        ├── Localization
        │   └── XComLongWarCommunityEdition.int
        ├── LWCE_Install.txt
        └── README.txt

Might even work on macos/darwin with small modifications, untested.
Probably needs different replacements for i686Linux mesa.

Something like this should produce a release from master on any system
with docker:

            docker run --rm nixos/nix bash -c \
                'nix --extra-experimental-features "nix-command flakes" build github:chrishayesmu/XCOM-LW-CommunityEdition/nix ; tar c -C result .' > nix.lwce.tar

### CODE REVIEW

**Comment by moben** [comment]
Not sure if this is massively useful right now to anyone else or if I'm the only one on Linux.

**Review by chrishayesmu — COMMENTED** [review]
Thanks for your PR! I'm not familiar with nix at all, so some very basic questions/comments from me.

1. To be clear, this downloads the UDK, builds the packages, and copies them to an output directory? Can you add a top-level comment to the entry point (Makefile?) describing the process?
2. Since I know nothing about nix: would you say this setup is fairly idiomatic? Just wondering if this would be pretty easy to read for someone familiar with nix.
3. Is it possible to stick all this in a subdirectory? I'm working on writing a LWCE installer in the same repo, and it'd be nice if the build logic for that and the build logic for LWCE itself could be self-contained in their own areas.

**Comment by moben** [comment]
1. Yes, if wrapped in `nix` then it fetches the UDK. The meat is in the Makefile and script though, which can be used without nix, but then the UDK installer has to be passed in. I'll try writing some description of the whole setup and the depencencies.
2. I think it should be fairly idiomatic. I'm not the biggest nix expert yet but the only two "interesting" things are the setup to run everything completely headless and that the build is split in two stages to allow caching the UDK installation. I tried making it a bit more idiomatic still.
3. I can move it in a subdirectory if you prefer. It's slightly less ergonomic but not massively so. I did also drop two of the new files, which were only needed for compat with older nix versions.

**Comment by chrishayesmu** [comment]
Fantastic, these changes look great. Thanks very much for the commits and the speedy review!

**Pull request merged**
